import plugin from 'tailwindcss/plugin'
import defaultTheme from 'tailwindcss/defaultTheme'
import tacoAriaAttributes from './node_modules/@economic/taco/plugins/tailwindcss-aria-attributes.js'
import tacoGroupPeer from './node_modules/@economic/taco/plugins/tailwindcss-group-peer.js'

const colors = {
  transparent: 'transparent',
  current: 'currentColor',
  white: '#fff',
  black: '#1c1c1c',
  brand: { vismaRed: '#E70641', paleOrange: '#FFF5E5', sunsetOrange: '#E89C2E', midnightBlue: '#29283E', coolBlue: '#F5F7F9' },
  grey: { lightest: '#fafafa', light: '#F6F6F6', DEFAULT: '#EBEBEB', dark: '#DDDDDD', darker: '#ACACAC', darkest: '#595959', darkNew: '#a5a6a9', 50: '#fafafa', 100: '#F6F6F6', 200: '#EBEBEB', 300: '#DDDDDD', 500: '#ACACAC', 700: '#595959', 900: '#303030' },
  purple: { lightest: '#585c74', light: '#4b4f64', DEFAULT: '#3d4153', dark: '#353a48', darker: '#29283e', darkest: '#212032', darkNew_1: '#373647', darkNew_2: '#414050', 100: '#EEE5FF', 200: '#ddd1ff', 300: '#CBBCFE', 500: '#9270FA', 700: '#6542D1', 900: '#412970' },
  blue: { lightest: '#DEEBFF', light: '#75A0F5', DEFAULT: '#4573D2', dark: '#2B57B4', 100: '#DEEBFF', 200: '#AACCFF', 300: '#75A0F5', 500: '#4573D2', 700: '#2B57B4', 900: '#29283E' },
  red: { lightest: '#FFDAD2', light: '#E66568', DEFAULT: '#CE3F42', dark: '#950027', 100: '#FFDAD2', 200: '#f3a09d', 300: '#E66568', 500: '#CE3F42', 700: '#950027', 900: '#64001B' },
  green: { lightest: '#cdf0e7', light: '#52C7AB', DEFAULT: '#08AE87', dark: '#028465', 100: '#cdf0e7', 200: '#9be1ce', 300: '#52C7AB', 500: '#08AE87', 700: '#028465', 900: '#14493A' },
  yellow: { lightest: '#FFF1C3', light: '#FFD665', DEFAULT: '#FFBD3B', dark: '#e89c2e', 100: '#FFF1C3', 200: '#ffe494', 300: '#FFD665', 500: '#FFBD3B', 700: '#e89c2e', 900: '#733700' },
  orange: { 100: '#FFE3BB', 200: '#FCCB80', 300: '#FAB64D', 500: '#F99702', 700: '#EF7D00', 900: '#4A2811' },
  brown: { 100: '#EEE0DA', 200: '#DFCCC2', 300: '#C4AB9E', 500: '#93715D', 700: '#73503B', 900: '#45291F' },
  pink: { 100: '#FFE3F7', 200: '#fcb9e9', 300: '#F98EDB', 500: '#E165BF', 700: '#CF49AA', 900: '#870062' },
}

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./node_modules/@economic/taco/dist/**/*.{js,css}",
  ],
  theme: {
    colors,
    fontFamily: {
      display: ['Helvetica, Arial, sans-serif'],
      mono: ['Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace'],
    },
    extend: {
      cursor: { grab: 'grab', grabbing: 'grabbing' },
      listStyleType: { circle: 'circle' },
      spacing: { 18: '4.5rem', 88: '22rem', 104: '26rem', 112: '28rem', 120: '30rem', 128: '32rem', xs: '32rem', sm: '48rem', md: '64rem', lg: '80rem' },
      screens: { xs: '375px', ...defaultTheme.screens },
      borderRadius: { DEFAULT: '4px', none: '0px', sm: '2px', lg: '8px', xl: '12px', full: '9999px' },
      fontSize: { xl: ['20px', { lineHeight: '28px' }], '2xl': ['24px', { lineHeight: '32px' }], '3xl': ['30px', { lineHeight: '32px' }] },
      fontWeight: { normal: '400', bold: '700' },
      lineHeight: { snug: '20px', normal: '24px' },
    },
  },
  plugins: [
    tacoAriaAttributes,
    tacoGroupPeer,
    plugin(function ({ addUtilities, theme }) {
      addUtilities({
        '.fixed-center': { position: 'fixed', left: '50%', top: '50%', transform: 'translateX(-50%) translateY(-50%)' },
        '.fixed-center-x': { position: 'fixed', left: '50%', transform: 'translateX(-50%)' },
        '.fixed-center-y': { position: 'fixed', top: '50%', transform: 'translateY(-50%)' },
        '.absolute-center': { position: 'absolute', left: '50%', top: '50%', transform: 'translateX(-50%) translateY(-50%)' },
        '.absolute-center-x': { position: 'absolute', left: '50%', transform: 'translateX(-50%)' },
        '.absolute-center-y': { position: 'absolute', top: '50%', transform: 'translateY(-50%)' },
        '.break-word': { 'word-break': 'break-word' },
        // WCAG contrast combinations
        '.wcag-black': { background: theme('colors.black'), color: theme('colors.white') },
        '.wcag-white': { background: theme('colors.white'), color: theme('colors.black') },
        '.wcag-transparent': { background: 'rgba(28,28,28,0.08)', color: theme('colors.black') },
        '.wcag-grey-50': { background: theme('colors.grey.50'), color: theme('colors.black') },
        '.wcag-grey-100': { background: theme('colors.grey.100'), color: theme('colors.black') },
        '.wcag-grey-200': { background: theme('colors.grey.200'), color: theme('colors.black') },
        '.wcag-grey-300': { background: theme('colors.grey.300'), color: theme('colors.black') },
        '.wcag-grey-500': { background: theme('colors.grey.500'), color: theme('colors.black') },
        '.wcag-grey-700': { background: theme('colors.grey.700'), color: theme('colors.white') },
        '.wcag-grey-900': { background: theme('colors.grey.900'), color: theme('colors.white') },
        '.wcag-grey-darkNew': { background: theme('colors.grey.darkNew'), color: theme('colors.white') },
        '.wcag-grey-lightest': { background: theme('colors.grey.lightest'), color: theme('colors.white') },
        '.wcag-grey-light': { background: theme('colors.grey.light'), color: theme('colors.white') },
        '.wcag-grey': { background: theme('colors.grey.DEFAULT'), color: theme('colors.white') },
        '.wcag-grey-dark': { background: theme('colors.grey.dark'), color: theme('colors.white') },
        '.wcag-grey-darker': { background: theme('colors.grey.darker'), color: theme('colors.white') },
        '.wcag-grey-darkest': { background: theme('colors.grey.darkest'), color: theme('colors.white') },
        '.wcag-pink-100': { background: theme('colors.pink.100'), color: theme('colors.pink.900') },
        '.wcag-pink-200': { background: theme('colors.pink.200'), color: theme('colors.pink.900') },
        '.wcag-pink-300': { background: theme('colors.pink.300'), color: theme('colors.pink.900') },
        '.wcag-pink-500': { background: theme('colors.pink.500'), color: theme('colors.black') },
        '.wcag-pink-700': { background: theme('colors.pink.700'), color: theme('colors.white') },
        '.wcag-pink-900': { background: theme('colors.pink.900'), color: theme('colors.white') },
        '.wcag-purple-100': { background: theme('colors.purple.100'), color: theme('colors.purple.900') },
        '.wcag-purple-200': { background: theme('colors.purple.200'), color: theme('colors.purple.900') },
        '.wcag-purple-300': { background: theme('colors.purple.300'), color: theme('colors.purple.900') },
        '.wcag-purple-500': { background: theme('colors.purple.500'), color: theme('colors.white') },
        '.wcag-purple-700': { background: theme('colors.purple.700'), color: theme('colors.white') },
        '.wcag-purple-900': { background: theme('colors.purple.900'), color: theme('colors.white') },
        '.wcag-purple-lightest': { background: theme('colors.purple.lightest'), color: theme('colors.white') },
        '.wcag-purple-light': { background: theme('colors.purple.light'), color: theme('colors.white') },
        '.wcag-purple': { background: theme('colors.purple.DEFAULT'), color: theme('colors.white') },
        '.wcag-purple-dark': { background: theme('colors.purple.dark'), color: theme('colors.white') },
        '.wcag-purple-darker': { background: theme('colors.purple.darker'), color: theme('colors.white') },
        '.wcag-purple-darkest': { background: theme('colors.purple.darkest'), color: theme('colors.white') },
        '.wcag-purple-darkNew_1': { background: theme('colors.purple.darkNew_1'), color: theme('colors.white') },
        '.wcag-purple-darkNew_2': { background: theme('colors.purple.darkNew_2'), color: theme('colors.white') },
        '.wcag-blue-lightest': { background: theme('colors.blue.lightest'), color: theme('colors.blue.dark') },
        '.wcag-blue-light': { background: theme('colors.blue.light'), color: theme('colors.white') },
        '.wcag-blue': { background: theme('colors.blue.DEFAULT'), color: theme('colors.white') },
        '.wcag-blue-dark': { background: theme('colors.blue.dark'), color: theme('colors.white') },
        '.wcag-blue-100': { background: theme('colors.blue.100'), color: theme('colors.blue.900') },
        '.wcag-blue-200': { background: theme('colors.blue.200'), color: theme('colors.blue.900') },
        '.wcag-blue-300': { background: theme('colors.blue.300'), color: theme('colors.blue.900') },
        '.wcag-blue-500': { background: theme('colors.blue.500'), color: theme('colors.white') },
        '.wcag-blue-700': { background: theme('colors.blue.700'), color: theme('colors.white') },
        '.wcag-blue-900': { background: theme('colors.blue.900'), color: theme('colors.white') },
        '.wcag-red-lightest': { background: theme('colors.red.lightest'), color: theme('colors.red.dark') },
        '.wcag-red-light': { background: theme('colors.red.light'), color: theme('colors.white') },
        '.wcag-red': { background: theme('colors.red.DEFAULT'), color: theme('colors.white') },
        '.wcag-red-dark': { background: theme('colors.red.dark'), color: theme('colors.white') },
        '.wcag-red-100': { background: theme('colors.red.100'), color: theme('colors.red.900') },
        '.wcag-red-200': { background: theme('colors.red.200'), color: theme('colors.red.900') },
        '.wcag-red-300': { background: theme('colors.red.300'), color: theme('colors.black') },
        '.wcag-red-500': { background: theme('colors.red.500'), color: theme('colors.white') },
        '.wcag-red-700': { background: theme('colors.red.700'), color: theme('colors.white') },
        '.wcag-red-900': { background: theme('colors.red.900'), color: theme('colors.white') },
        '.wcag-green-lightest': { background: theme('colors.green.lightest'), color: theme('colors.black') },
        '.wcag-green-light': { background: theme('colors.green.light'), color: theme('colors.black') },
        '.wcag-green': { background: theme('colors.green.DEFAULT'), color: theme('colors.white') },
        '.wcag-green-dark': { background: theme('colors.green.dark'), color: theme('colors.white') },
        '.wcag-green-100': { background: theme('colors.green.100'), color: theme('colors.green.900') },
        '.wcag-green-200': { background: theme('colors.green.200'), color: theme('colors.green.900') },
        '.wcag-green-300': { background: theme('colors.green.300'), color: theme('colors.green.900') },
        '.wcag-green-500': { background: theme('colors.green.500'), color: theme('colors.black') },
        '.wcag-green-700': { background: theme('colors.green.700'), color: theme('colors.white') },
        '.wcag-green-900': { background: theme('colors.green.900'), color: theme('colors.white') },
        '.wcag-yellow-lightest': { background: theme('colors.yellow.lightest'), color: theme('colors.black') },
        '.wcag-yellow-light': { background: theme('colors.yellow.light'), color: theme('colors.black') },
        '.wcag-yellow': { background: theme('colors.yellow.DEFAULT'), color: theme('colors.black') },
        '.wcag-yellow-dark': { background: theme('colors.yellow.dark'), color: theme('colors.white') },
        '.wcag-yellow-100': { background: theme('colors.yellow.100'), color: theme('colors.yellow.900') },
        '.wcag-yellow-200': { background: theme('colors.yellow.200'), color: theme('colors.yellow.900') },
        '.wcag-yellow-300': { background: theme('colors.yellow.300'), color: theme('colors.yellow.900') },
        '.wcag-yellow-500': { background: theme('colors.yellow.500'), color: theme('colors.yellow.900') },
        '.wcag-yellow-700': { background: theme('colors.yellow.700'), color: theme('colors.black') },
        '.wcag-yellow-900': { background: theme('colors.yellow.900'), color: theme('colors.white') },
        '.wcag-brown-100': { background: theme('colors.brown.100'), color: theme('colors.brown.900') },
        '.wcag-brown-200': { background: theme('colors.brown.200'), color: theme('colors.brown.900') },
        '.wcag-brown-300': { background: theme('colors.brown.300'), color: theme('colors.brown.900') },
        '.wcag-brown-500': { background: theme('colors.brown.500'), color: theme('colors.white') },
        '.wcag-brown-700': { background: theme('colors.brown.700'), color: theme('colors.white') },
        '.wcag-brown-900': { background: theme('colors.brown.900'), color: theme('colors.white') },
        '.wcag-orange-100': { background: theme('colors.orange.100'), color: theme('colors.orange.900') },
        '.wcag-orange-200': { background: theme('colors.orange.200'), color: theme('colors.orange.900') },
        '.wcag-orange-300': { background: theme('colors.orange.300'), color: theme('colors.orange.900') },
        '.wcag-orange-500': { background: theme('colors.orange.500'), color: theme('colors.orange.900') },
        '.wcag-orange-700': { background: theme('colors.orange.700'), color: theme('colors.orange.900') },
        '.wcag-orange-900': { background: theme('colors.orange.900'), color: theme('colors.white') },
        '.wcag-brand-vismaRed': { background: theme('colors.brand.vismaRed'), color: theme('colors.white') },
        '.wcag-brand-paleOrange': { background: theme('colors.brand.paleOrange'), color: theme('colors.orange.900') },
        '.wcag-brand-sunsetOrange': { background: theme('colors.brand.sunsetOrange'), color: theme('colors.yellow.900') },
        '.wcag-brand-midnightBlue': { background: theme('colors.brand.midnightBlue'), color: theme('colors.white') },
        '.wcag-brand-coolBlue': { background: theme('colors.brand.coolBlue'), color: theme('colors.blue.900') },
        // Legacy utilities
        '.yt-transparent': { background: theme('colors.transparent'), color: theme('colors.blue.500') },
        '.yt-focus': { 'box-shadow': `0 0 0 1px #fff, 0 0 0 3px ${theme('colors.blue.500')}`, outline: 'none' },
        '.yt-focus-inset': { 'box-shadow': `inset 0 0 0 2px ${theme('colors.blue.500')}`, outline: 'none' },
        '.yt-focus-dark': { 'box-shadow': `0 0 0 3px ${theme('colors.blue.500')}`, outline: 'none' },
        '.yt-focus-green': { 'box-shadow': '0 0 0 0.15rem rgba(0, 213, 165, 0.25)', outline: 'none' },
        '.yt-focus-yellow': { 'box-shadow': '0 0 0 0.15rem rgba(239, 125, 0, 0.25)', outline: 'none' },
        '.yt-focus-red': { 'box-shadow': '0 0 0 0.15rem rgba(253, 99, 97, 0.25)', outline: 'none' },
        '.yt-blue-solid': { background: theme('colors.blue.500'), color: theme('colors.white') },
        '.yt-blue-inverted': { background: theme('colors.transparent'), border: `1px solid ${theme('colors.blue.500')}`, color: theme('colors.blue.500') },
        '.yt-yellow-solid': { background: theme('colors.yellow.500'), color: theme('colors.black') },
        '.yt-yellow-inverted': { background: theme('colors.transparent'), border: `1px solid ${theme('colors.yellow.700')}`, color: theme('colors.yellow.700') },
        '.yt-red-solid': { background: theme('colors.red.500'), color: theme('colors.white') },
        '.yt-red-inverted': { background: theme('colors.transparent'), border: `1px solid ${theme('colors.red.500')}`, color: theme('colors.red.500') },
        '.yt-green-solid': { background: theme('colors.green.700'), color: theme('colors.white') },
        '.yt-green-inverted': { background: theme('colors.transparent'), border: `1px solid ${theme('colors.green.700')}`, color: theme('colors.green.700') },
        '.yt-grey-solid': { background: theme('colors.grey.200'), color: theme('colors.black') },
        '.yt-grey-inverted': { background: theme('colors.transparent'), border: `1px solid ${theme('colors.grey.700')}`, color: theme('colors.grey.700') },
        '.yt-shadow': { 'box-shadow': '0px 1px 3px 1px rgba(89, 85, 98, 0.35), 0px 0px 1px 0px rgba(89, 85, 98, 0.2)' },
        '.yt-shadow-inset': { 'box-shadow': 'inset 0px 1px 4px 0px rgba(89, 85, 98, 0.3), inset 0px 0px 1px 0px rgba(89, 85, 98, 0.2)' },
        '.pointer-events-all': { 'pointer-events': 'all' },
      })
    }),
  ],
}
